[project]
name = "universal iramuteq tagger"
version = "0.1.0"
description = "This script automates Iramuteq tagging by passing texts through OpenAI API given a set of predefined tags/subtags"
requires-python = ">=3.11"
dependencies = [
    "openai>=1.65.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "rapidfuzz>=3.12.1",
    "streamlit>=1.42.2",
]
